/** ISO 3166-1 alpha-2 codes for country-flag-icons (England/Scotland use custom SVGs). */
export const TEAM_ISO: Record<string, string> = {
  Algeria: 'DZ',
  Argentina: 'AR',
  Australia: 'AU',
  Austria: 'AT',
  Belgium: 'BE',
  Bosnia: 'BA',
  Brazil: 'BR',
  Canada: 'CA',
  'Cape Verde': 'CV',
  Colombia: 'CO',
  Congo: 'CD',
  Croatia: 'HR',
  Curacao: 'CW',
  Czechia: 'CZ',
  Ecuador: 'EC',
  Egypt: 'EG',
  England: 'ENG',
  France: 'FR',
  Germany: 'DE',
  Ghana: 'GH',
  Haiti: 'HT',
  Iran: 'IR',
  Iraq: 'IQ',
  'Ivory Coast': 'CI',
  Japan: 'JP',
  Jordan: 'JO',
  Korea: 'KR',
  Mexico: 'MX',
  Morocco: 'MA',
  Netherlands: 'NL',
  'New Zealand': 'NZ',
  Norway: 'NO',
  Panama: 'PA',
  Paraguay: 'PY',
  Portugal: 'PT',
  Qatar: 'QA',
  'Saudi Arabia': 'SA',
  Scotland: 'SCT',
  Senegal: 'SN',
  'South Africa': 'ZA',
  Spain: 'ES',
  Sweden: 'SE',
  Switzerland: 'CH',
  Tunisia: 'TN',
  Turkey: 'TR',
  Uruguay: 'UY',
  USA: 'US',
  Uzbekistan: 'UZ',
};

export function getTeamIso(team: string): string | undefined {
  return TEAM_ISO[team];
}
